### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by tesseract-two** [oMaN-Rod/nxDumpFuse#1]
Hello! Just that one Linux user asking for Linux support. I come from the [yuzu Quickstart Guide rewrite pr](https://github.com/yuzu-emu/yuzu-emu.github.io/pull/325) where this replaces nxDumpMerger. Thanks for making this, and have a good day.

**Comment by oMaN-Rod** [comment]
Hi! Added to the [latest release](https://github.com/oMaN-Rod/nxDumpFuse/releases/tag/v1.0.3)

**Comment by tesseract-two** [comment]
Thank you!
