### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by BogTheMudWing** [oMaN-Rod/nxDumpFuse#2]
I'm trying to run nxDumpFuse on Linux Mint 21.1 (based on Ubuntu) and I'm running into this issue when trying to run nxDumpFuse from the terminal:
```
No usable version of libssl was found
Aborted (core dumped)
```
Opening it normally does nothing. I saw something about `nxDumpFuse.sh` and `Run Executable.desktop` files on the Wiki page, but they aren't in the release.
Do I need to install something? I tried running the Windows version through Wine, but it crashed as well.

**Comment by fahhem** [comment]
It seems like you need libssl1, which isn't available on some modern Linux distributions. For Ubuntu 23.04, I managed to fix this with:

```
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
```

**Comment by BogTheMudWing** [comment]
Thank you so much!

**Comment by TheXug** [comment]
Adding this for people who have this problem in the future specifically on Bazzite (you have to manually create a library for v1 of openssl):

```
# Create a directory for the library
mkdir -p ~/.local/lib

# Download and extract the library from AlmaLinux 8 (compatible with Fedora)
cd /tmp
wget https://repo.almalinux.org/almalinux/8/AppStream/x86_64/os/Packages/compat-openssl10-1.0.2o-4.el8_6.x86_64.rpm

# Extract the RPM
rpm2cpio compat-openssl10-1.0.2o-4.el8_6.x86_64.rpm | cpio -idmv

# Copy the libraries to your local lib directory
cp ./usr/lib64/libssl.so.10 ./usr/lib64/libcrypto.so.10 ~/.local/lib/

# Clean up
cd ~
rm -rf /tmp/compat-openssl10*
```

Add the library path to your environment

```
# Add to your shell profile
echo 'export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH' >> ~/.bashrc

# Apply it to current session
export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH
```

And that should do it
