### ISSUE TITLE
Mac release

### ISSUE THREAD

**Issue by carameltaffy2** [oMaN-Rod/nxDumpFuse#3]
yea, i need a mac release because reasons. if you are unable to thats fine, its just i cant get any games running on ryujinx without this.

**Comment by oMaN-Rod** [comment]
I don't have a mac to test this version, let me know if it works and I will publish a release to include it. [nxDumpFuse.zip](https://github.com/oMaN-Rod/nxDumpFuse/files/13327023/nxDumpFuse.zip)

**Comment by carameltaffy2** [comment]
It seems to work, you just need to run it from the terminal. (i am presuming you only need to do this on macs above Catalina 10.15)
